name: Documentation

on:
  push:
    branches: [ master, main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Ensure you install these specifically if not in your [docs] extra
          # python -m pip install sphinx-autoapi sphinx-rtd-theme
          python -m pip install -e .[dev,docs]

      - name: Build Sphinx Documentation
        run: |
          # 1. Force the PYTHONPATH to the current directory. 
          # This helps 'viewcode' link to local files instead of site-packages.
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          
          # 2. Clean previous builds to avoid stale API files
          rm -rf docs/build_docs/
          
          make docs DOC_OUT=./docs/build_docs/
          
          touch ./docs/build_docs/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./docs/build_docs
          branch: gh-pages